# 点数设置
# 如果有指定最小值或最大值，则分配的点数为随机生成的最小值~最大值之间的数字。
points:
    # 点数设置 - 分配
    upgrade:
        # 权限组
        user:
            # 普通玩家 (默认)
            normal:
                # 每次分配获得的属性加成最小值
                min: 1
                # 每次分配获得的属性加成最大值
                max: 10
            # 会员玩家
            vip:
                min: 5
                max: 20
    # 点数设置 - 来源
    earn:
        # 战斗类
        battle: 
            # 是否可以通过战斗来获得分配点数
            enabled: true
            # 最小获得点数
            min: 1
            # 最大获得点数
            max: 5
            # 越级额外奖励
            widegap:
                enabled: true
                # 双方差距多少级触发越级战斗判定
                threshold: 5
                # 当双方等级差距5级以上时
                # 如果要设置相差6级以上，可以复制一份，并把5改成6
                5:
                    min: 2
                    max: 5
                # 如果没有规定某等级触发的奖励，则使用下面的规则
                other:
                    min: 3
                    max: 5